table gold_weekly_rankings
	lineageTag: 0f656995-eb55-4220-a19b-59f6b288b13d
	sourceLineageTag: [dbo].[gold_weekly_rankings]

	measure 'Top 10 Tracks' = COUNTROWS(FILTER(gold_weekly_rankings, gold_weekly_rankings[is_top10] = TRUE()))
		formatString: 0
		lineageTag: a845bc1e-625f-4806-88f8-58a7700b014c

		changedProperty = Name

	column region
		dataType: string
		lineageTag: 8f315df1-18e6-4b1e-9404-37ad5d9194b9
		sourceLineageTag: region
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 780d28d3-5d85-4878-9965-b23f1b664dd1
		sourceLineageTag: rank
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column track_id
		dataType: string
		lineageTag: 5cf51874-104b-4834-be05-fe7c35a636b0
		sourceLineageTag: track_id
		summarizeBy: none
		sourceColumn: track_id

		annotation SummarizationSetBy = Automatic

	column track_name
		dataType: string
		lineageTag: fe4808a4-17df-4b03-af2d-0dfd0eacb467
		sourceLineageTag: track_name
		summarizeBy: none
		sourceColumn: track_name

		annotation SummarizationSetBy = Automatic

	column primary_artist
		dataType: string
		lineageTag: 8fd70965-9861-4827-9e2e-a988e4268b62
		sourceLineageTag: primary_artist
		summarizeBy: none
		sourceColumn: primary_artist

		annotation SummarizationSetBy = Automatic

	column track_genre
		dataType: string
		lineageTag: f53ee50b-1e01-4b3c-b607-d6a7edcf47d2
		sourceLineageTag: track_genre
		summarizeBy: none
		sourceColumn: track_genre

		annotation SummarizationSetBy = Automatic

	column streams
		dataType: int64
		formatString: 0
		lineageTag: e9d0b4de-501d-4472-80ad-6bf9e411a191
		sourceLineageTag: streams
		summarizeBy: sum
		sourceColumn: streams

		annotation SummarizationSetBy = Automatic

	column trend
		dataType: string
		lineageTag: b6bbecf0-7fcd-4328-bf3e-38779e3528d7
		sourceLineageTag: trend
		summarizeBy: none
		sourceColumn: trend

		annotation SummarizationSetBy = Automatic

	column is_top10
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b663842f-52d4-45d6-a072-ed77fcf232fb
		sourceLineageTag: is_top10
		summarizeBy: none
		sourceColumn: is_top10

		annotation SummarizationSetBy = Automatic

	column is_rising
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8a2217e3-98de-4069-bf65-44596ba0abab
		sourceLineageTag: is_rising
		summarizeBy: none
		sourceColumn: is_rising

		annotation SummarizationSetBy = Automatic

	column danceability
		dataType: double
		lineageTag: 84455889-61f0-4938-8872-3dac3393b38b
		sourceLineageTag: danceability
		summarizeBy: sum
		sourceColumn: danceability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column energy
		dataType: double
		lineageTag: 9cbca895-da6d-4fb3-85d6-b2891c81f7ed
		sourceLineageTag: energy
		summarizeBy: sum
		sourceColumn: energy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valence
		dataType: double
		lineageTag: 84eeda82-90cc-4019-9563-89d364c80adc
		sourceLineageTag: valence
		summarizeBy: sum
		sourceColumn: valence

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mood
		dataType: string
		lineageTag: 77189b97-b272-40fd-b3cd-e2048450a2e0
		sourceLineageTag: mood
		summarizeBy: none
		sourceColumn: mood

		annotation SummarizationSetBy = Automatic

	column energy_level
		dataType: string
		lineageTag: 3ef7644f-91a6-420f-b902-a2f5f6b74f54
		sourceLineageTag: energy_level
		summarizeBy: none
		sourceColumn: energy_level

		annotation SummarizationSetBy = Automatic

	partition gold_weekly_rankings = entity
		mode: directLake
		source
			entityName: gold_weekly_rankings
			schemaName: dbo
			expressionSource: 'DirectLake - spotify_lh'

